#! /bin/bash

echo  Downloading the hash to compare 


echo complete 


NEWHASH="$(curl -L 'https://github.com'$(curl -Ls  https://github.com/go-gitea/gitea/releases/latest | grep '\.*linux-amd64.sha256' | cut -d\" -f2  | head -1  ) |  cut -d " " -f 1)"
OLDHASH="$(sha256sum gitea | cut -d " " -f 1)"


if [ "$NEWHASH" !=  "$OLDHASH" ];
then
    echo Hashes are differnt ! An update is out. 

    echo backing up

    tar -cf /var/gitea/backups/giteabackup.tar /home/git

    echo removing old exucutable 
    rm -f gitea

    echo   downloading new one

    
    version=$(curl -v https://github.com/go-gitea/gitea/releases/latest 2>&1 | grep "^< Location:" | tr -d '\r' | grep -Eo "/v([0-9]|\.)+$" | sed 's|/v||')
    wget -q -O gitea https://github.com/go-gitea/gitea/releases/download/v"$version"/gitea-"$version"-linux-amd64


    echo exucting..
    chmod +x gitea

    ./gitea web &
#the following python code sends an email not sure why I decided to use python for this..

#********************************start of python code******************************
  python - << END

 import smtplib

 print('sending update email')

 smtp0bj = smtplib.SMTP('smtp.gmail.com', 587)
 smtp0bj.starttls()
 smtp0bj.login('***REMOVED***', '***REMOVED***')
 smtp0bj.sendmail('***REMOVED***', '***REMOVED***', 'Subject: giteaupdated\nwow gitea has updated')
 smtp0bj.quit()

END

#******************************** end of python code******************************


else
echo There is no update

#********************************start of python code******************************
  python - << END

import smtplib

print('sending update email')

smtp0bj = smtplib.SMTP('smtp.gmail.com', 587)
smtp0bj.starttls()
smtp0bj.login('***REMOVED***', '***REMOVED***')
smtp0bj.sendmail('***REMOVED***', '***REMOVED***', 'Subject: nogiteaupdate\ngitea checked for an update but there was not one')
smtp0bj.quit()

END

#********************************end of python code******************************


fi
